### PR TITLE
Remove ActiveSupport dependency (rebased)

### PR DESCRIPTION
**Pull request by pat**
This is the rebased version of #65 (I've inherited a project from @timriley that uses his fork, hence it's in my best interests to get all of this merged in as well 😁). All the hard work is Tim's, all I've done is rebased and fixed merged conflicts (I think they're all correct - the tests are green on my machine 🤞🏻)

### CODE REVIEW

**Comment by timriley** [comment]
Thank you, @pat!

**Comment by Empact** [comment]
Thanks Pat, I expect to be able to merge and release this over the next week or so.

**Comment by pat** [comment]
Oh good, that gives me a bit of time to get a PR for the test suite working on Ruby 3 as well 😅

**Comment by Empact** [comment]
Another rebase, please?

**Comment by pat** [comment]
@Empact done :)

**Comment by Empact** [comment]
Merged as https://github.com/Empact/roxml/commit/0bc78e6a0fa95a78815b4939215229e0116de9af 

A mere 3 years after promised. :P

**Comment by pat** [comment]
Thanks @Empact - no stress about the delay, I know I have some long-outstanding things to deal with on my own OSS projects too!

**Pull request closed without merging**
