### PR TITLE
Fixed the warning of deprecation URI.escape and URI.unescape for Ruby 2.7.x

### PR DESCRIPTION
**Pull request by ibrahim-saifee**
Used decode_www_form_component and encode_www_form_component for URL encoding/decoding.

### CODE REVIEW

**Comment by amitminfobeans** [comment]
We can merge this PR as this method removed the warning for me.
@Empact  Please have a look and merge it. if it looks good.

**Review by anthonyhamou — COMMENTED** [review]
It seems to be correct

**Comment by yld** [comment]
Is there any release plan to include this fix?

**Comment by anthonyhamou** [comment]
Hello @Empact and also @ibrahim-saifee @amitminfobeans @yld 
Could you please push an updated gem release to RubyGems that we can then reference in our gemspec ?
The latest version of roxml is 4.1.1 from July 6, 2020
https://rubygems.org/gems/roxml
Thank you !

**Pull request merged**
