### PR TITLE
Add support for Ruby 3

### PR DESCRIPTION
**Pull request by pat**
Please do note the two main commits - adding rexml as a development dependency (but perhaps it should be a runtime dependency?), and switching URI.escape/unescape to the CGI equivalents, as the former have been removed in Ruby 3. Would appreciate suggestions/changes by those with more knowledge :)

### CODE REVIEW

**Comment by givigier** [comment]
:+1:

**Comment by Empact** [comment]
Could you please rebase?

**Comment by Empact** [comment]
Thanks @pat!

**Comment by pat** [comment]
No worries - you just happened to catch me while I'm in the midst of some other open source work :) Rebased #75 as well.

**Comment by Empact** [comment]
Applied to master directly e.g. 23c9ab68fe3d36595e3f4c49567ab876c9f6ff12

**Pull request closed without merging**
